name: purriorities
description: A Flutter frontend for Purriorities time management gamification app.
publish_to: 'none'
version: 0.0.1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  go_router: ^7.1.1
  provider: ^6.0.5
  json_annotation: ^4.8.1
  intl: ^0.18.1
  dio: ^5.1.2
  dio_cookie_manager: ^3.0.0
  cookie_jar: ^4.0.3
  flutter_secure_storage: ^8.0.0
  flutter_slidable: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  build_runner: ^2.4.4
  json_serializable: ^6.7.0

flutter:
  uses-material-design: true
  assets:
    - assets/gray-cat.webp
    - assets/gray-cat-animated.webp
    - assets/foods-fish.webp
    - assets/foods-fish-animated.webp
    - assets/valerian.webp
    - assets/valerian-animated.webp